database:
    driver: postgres
    host: host.docker.internal
    port: 5432
    user: postgres
    password: 123
    dbname: postgres
    sslmode: disable
    schema: 
        listclinics: listclinics
sentry:
    isactive: true
    dsn: https://xxx@sentry.medkomtek.com/22
server:
    port: 8080
    issuer: hayvee
    env: development
    baseurl: http://localhost:8081/
    redirectpage: http://localhost:8081/