database:
    driver: postgres
    host: 103.214.112.202
    port: 5434
    user: postgres
    password: Kalahkan
    dbname: hayvee
    sslmode: disable
    schema: 
        listclinics: listclinics
        user: user
sentry:
    isactive: true
    dsn: https://xxx@sentry.medkomtek.com/22
server:
    port: 8080
    issuer: hayvee
    env: development
    baseurl: http://localhost:8080/
    redirectpage: http://localhost:8080/